Controllers/BrandsController.cs
using System.Drawing.Drawing2D;
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures.Controllers
{
	[IgnoreAntiforgeryToken]
	public class BrandsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public BrandsController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of all brands.
		/// </summary>
		/// <returns>A view with the list of brands.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Index()
		{
			return View(await _context.Brands.ToListAsync());
		}

		/// <summary>
		/// Gets the details of a specific brand.
		/// </summary>
		/// <param name="id">The ID of the brand.</param>
		/// <returns>A partial view with the brand details.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var brand = await _context.Brands
				.FirstOrDefaultAsync(m => m.Id == id);
			if (brand == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", brand);
		}

		/// <summary>
		/// Shows the create brand form.
		/// </summary>
		/// <returns>A partial view with the create brand form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public IActionResult Create()
		{
			return PartialView("_CreatePartial");
		}

		/// <summary>
		/// Creates a new brand.
		/// </summary>
		/// <param name="brand">The brand to create.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create partial view.</returns>
		[Authorize]
		[HttpPost]
		public async Task<IActionResult> Create([Bind("Id,Name")] Brand brand)
		{
			ModelState.Remove("Models");

			if (string.IsNullOrWhiteSpace(brand.Name))
			{
				ModelState.AddModelError("Name", "Le nom de la marque est requis.");
				return PartialView("_CreatePartial", brand);
			}

			var existingBrand = await _context.Brands
				.FirstOrDefaultAsync(b => b.Name.ToLower() == brand.Name.ToLower());

			if (existingBrand != null)
			{
				ModelState.AddModelError("Name", "Une marque avec ce nom existe déjà.");
			}

			if (ModelState.IsValid)
			{
				_context.Add(brand);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			return PartialView("_CreatePartial", brand);
		}

		/// <summary>
		/// Shows the edit brand form.
		/// </summary>
		/// <param name="id">The ID of the brand to edit.</param>
		/// <returns>A partial view with the edit brand form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var brand = await _context.Brands.FindAsync(id);
			if (brand == null)
			{
				return NotFound();
			}
			return PartialView("_EditPartial", brand);
		}

		/// <summary>
		/// Edits a specific brand.
		/// </summary>
		/// <param name="id">The ID of the brand to edit.</param>
		/// <param name="brand">The updated brand information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit partial view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Brand brand)
		{
			if (id != brand.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(brand);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!BrandExists(brand.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return PartialView("_EditPartial", brand);
		}

		/// <summary>
		/// Shows the delete brand confirmation form.
		/// </summary>
		/// <param name="id">The ID of the brand to delete.</param>
		/// <returns>A partial view with the delete brand confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var brand = await _context.Brands
				.FirstOrDefaultAsync(m => m.Id == id);
			if (brand == null)
			{
				return NotFound();
			}

			return PartialView("_DeletePartial", brand);
		}

		/// <summary>
		/// Deletes a specific brand.
		/// </summary>
		/// <param name="id">The ID of the brand to delete.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var brand = await _context.Brands.FindAsync(id);
                if (brand != null)
                {
                    _context.Brands.Remove(brand);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorDeleteMessage"] = "Cette marque ne peut pas être supprimée car elle est utilisée pour un ou plusieurs véhicules, ou elle contient des modèles et finitions.\n Veuillez supprimer ces éléments avant de procéder.";
                return RedirectToAction(nameof(Index));
            }
        }

        /// <summary>
        /// Checks if a brand exists.
        /// </summary>
        /// <param name="id">The ID of the brand to check.</param>
        /// <returns>True if the brand exists, otherwise false.</returns>
        private bool BrandExists(int id)
		{
			return _context.Brands.Any(e => e.Id == id);
		}
	}
}

Controllers/VehiclesController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.PixelFormats;

namespace ExpressVoitures.Controllers
{
	[IgnoreAntiforgeryToken]
	public class VehiclesController : Controller
	{
		private readonly ApplicationDbContext _context;

		public VehiclesController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of vehicles.
		/// </summary>
		/// <returns>A view with the list of vehicles.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle")]
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
				.Include(v => v.Repairs);

            return View(await applicationDbContext.ToListAsync());
		}

		/// <summary>
		/// Gets the details of a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A partial view with the vehicle details.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/details")]
		public async Task<IActionResult> Details(int id)
		{
			var vehicle = await _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
                .Include(v => v.Repairs)
                .FirstOrDefaultAsync(m => m.Id == id);

			if (vehicle == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", vehicle);
		}

		/// <summary>
		/// Shows the create vehicle form.
		/// </summary>
		/// <returns>A view with the create vehicle form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/add")]
		public IActionResult Create()
		{
			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name");
			return View();
		}

		/// <summary>
		/// Creates a new vehicle.
		/// </summary>
		/// <param name="vehicle">The vehicle to create.</param>
		/// <param name="ImagePath">The image file to upload.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/add")]
		public async Task<IActionResult> Create([Bind("Id,Vin,Year,PurchaseDate,PurchasePrice,AvailabilityDate,SaleDate,BrandId,ModelId,TrimLevelId,Description")] Vehicle vehicle, IFormFile ImagePath)
		{
			if (ImagePath != null && ImagePath.Length > 0)
			{
				var extension = Path.GetExtension(ImagePath.FileName);

				var fileName = Path.GetFileNameWithoutExtension(ImagePath.FileName);
				fileName = fileName.Replace(" ", "-");
				fileName = string.Concat(fileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)));
				fileName = $"{fileName}_{DateTime.Now:yyyyMMddHHmmss}{extension}".ToLower();

				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/adverts", fileName);

				using (var image = await SixLabors.ImageSharp.Image.LoadAsync<Rgba32>(ImagePath.OpenReadStream()))
				{
					// Redimensionner l'image à 800x600
					image.Mutate(x => x.Resize(new ResizeOptions
					{
						Size = new Size(800, 600),
						Mode = ResizeMode.Crop
					}));

					await image.SaveAsync(filePath, new JpegEncoder());
				}

				vehicle.ImagePath = "/images/adverts/" + fileName;
			}

			ModelState.Remove("Brand");
			ModelState.Remove("Model");
			ModelState.Remove("TrimLevel");
			ModelState.Remove("ImagePath");
			if (ModelState.IsValid)
			{
				_context.Add(vehicle);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Shows the edit vehicle form for a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A view with the edit vehicle form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/edit")]
		public async Task<IActionResult> Edit(int id)
		{
			var vehicle = await _context.Vehicle.FindAsync(id);
			if (vehicle == null)
			{
				return NotFound();
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Edits a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <param name="vehicle">The updated vehicle information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit view.</returns>
		[Authorize]
		[HttpPost("/admin/vehicle/{id}/edit")]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Vin,Year,PurchaseDate,PurchasePrice,AvailabilityDate,SaleDate,BrandId,ModelId,TrimLevelId,Description")] Vehicle vehicle, IFormFile ImagePath)
		{
			if (id != vehicle.Id)
			{
				return NotFound();
			}

			var existingVehicle = await _context.Vehicle.AsNoTracking().FirstOrDefaultAsync(v => v.Id == id);
			if (existingVehicle == null)
			{
				return NotFound();
			}

			if (ImagePath != null && ImagePath.Length > 0)
			{
				var extension = Path.GetExtension(ImagePath.FileName);

				var fileName = Path.GetFileNameWithoutExtension(ImagePath.FileName);
				fileName = fileName.Replace(" ", "-");
				fileName = string.Concat(fileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)));
				fileName = $"{fileName}_{DateTime.Now:yyyyMMddHHmmss}{extension}".ToLower();

				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/adverts", fileName);

				using (var image = await Image.LoadAsync<Rgba32>(ImagePath.OpenReadStream()))
				{
					var destWidth = 1280;
					var destHeight = 720;

					// Calculate cropping rectangle
					var cropRect = new Rectangle(0, 0, image.Width, image.Height);
					if ((image.Width / (double)image.Height) > (16 / 9.0))
					{
						var newWidth = (int)(image.Height * (16 / 9.0));
						cropRect.X = (image.Width - newWidth) / 2;
						cropRect.Width = newWidth;
					}
					else
					{
						var newHeight = (int)(image.Width * (9 / 16.0));
						cropRect.Y = (image.Height - newHeight) / 2;
						cropRect.Height = newHeight;
					}

					// Crop and resize the image
					image.Mutate(x => x
						.Crop(cropRect)
						.Resize(destWidth, destHeight));

					await image.SaveAsync(filePath, new JpegEncoder());
				}

				vehicle.ImagePath = "/images/adverts/" + fileName;
			}
			else
			{
				vehicle.ImagePath = existingVehicle.ImagePath;
			}

			ModelState.Remove("Brand");
			ModelState.Remove("Model");
			ModelState.Remove("TrimLevel");
			ModelState.Remove("ImagePath");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(vehicle);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!VehicleExists(vehicle.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Shows the delete vehicle confirmation form for a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A partial view with the delete vehicle confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/delete")]
		public async Task<IActionResult> Delete(int id)
		{
			var vehicle = await _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (vehicle == null)
			{
				return NotFound();
			}

			return PartialView("_DeletePartial", vehicle);
		}

		/// <summary>
		/// Deletes a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/{id}/delete"), ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var vehicle = await _context.Vehicle.FindAsync(id);
			if (vehicle != null)
			{
				_context.Vehicle.Remove(vehicle);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		/// <summary>
		/// Checks if a vehicle exists.
		/// </summary>
		/// <param name="id">The ID of the vehicle to check.</param>
		/// <returns>True if the vehicle exists, otherwise false.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		private bool VehicleExists(int id)
		{
			return _context.Vehicle.Any(e => e.Id == id);
		}

		/// <summary>
		/// Gets the models based on BrandId.
		/// </summary>
		/// <param name="brandId">The ID of the brand.</param>
		/// <returns>A JSON result with the list of models.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<JsonResult> GetModelsByBrand(int brandId)
		{
			var models = await _context.Models.Where(m => m.BrandId == brandId).ToListAsync();
			return Json(new SelectList(models, "Id", "Name"));
		}

		/// <summary>
		/// Gets the trim levels based on ModelId.

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Express Voitures</title>

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.0/dist/bootstrap-table.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/themes/base/theme.min.css" integrity="sha512-XutDejX3PkIxnMh/xEu11qZ9+jn3lh+SrEnbtXny8dhr7Jk+lBkr2ujwco0Bx4LJ500XibluwyXc0kOJ+oY51Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ExpressVoitures.styles.css" asp-append-version="true" />

</head>
<body class="@ViewData["BodyClass"]">
	<header>
		<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Express Voitures</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" asp-area="" asp-controller="Home" asp-action="Adverts">Annonces</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">A propos</a>
						</li>
					</ul>
					
					<ul class="navbar-nav">
						@if (SignInManager.IsSignedIn(User))
						{
							<li class="nav-item dropdown admin me-2">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Admin
								</a>
								<ul class="dropdown-menu">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Vehicles" asp-action="Index">
											Les voitures
										</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Vehicles" asp-action="Create">
											Ajouter un véhicule
										</a>
									</li>
									<li><hr class="dropdown-divider"></li>
									<li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Brands" asp-action="Index">
											Les marques
										</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Models" asp-action="Index">
											Les modèles
										</a>
									</li>
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="TrimLevels" asp-action="Index">
											Les finitions
										</a>
									</li>
								</ul>
							</li>
						}

						<partial name="_LoginPartial" />
					</ul>
				</div>
			</div>
		</nav>
	</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

	<footer class="footer">
		<div class="container text-center">
			<span>@DateTime.Now.Year &copy; Express Vehicles - Tous droits réservés - </span>
			<a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-decoration-none text-danger">A propos</a>
		</div>
	</footer>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.3/jquery-ui.min.js" integrity="sha512-Ww1y9OuQ2kehgVWSD/3nhgfrb424O3802QYP/A5gPXoM4+rRjiKrjHdGxQKrMGQykmsJ/86oGdHszfcVgUr4hA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.0/dist/bootstrap-table.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.0/dist/bootstrap-table-locale-all.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>