Models/Brand.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
	[Display(Name = "Marque")]
	public class Brand
	{
        [Key]
        public int Id { get; set; }

		[Display(Name = "Marque")]
		public string Name { get; set; } = string.Empty;

		[NotMapped]
		[Display(Name = "Modèle")]
		public virtual ICollection<Model>? Models { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace ExpressVoitures.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Model.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
	[Display(Name = "Modèle")]
	public class Model
	{
        [Key]
        public int Id { get; set; }

		[Display(Name = "Modèle")]
		public string Name { get; set; } = string.Empty;

		[NotMapped]
		[Display(Name = "Marque")]
		public int BrandId { get; set; }
		public virtual Brand? Brand { get; set; }

		[NotMapped]
		public virtual ICollection<TrimLevel>? TrimLevels { get; set; }
    }
}

Models/Repair.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
    [Display(Name = "Réparation")]
    public class Repair
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Réparation")]
        [Required(ErrorMessage = "La réparation doit être complétée.")]
        public string Name { get; set; } = string.Empty;

		[Display(Name = "Coût")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Le coût doit être supérieur à 0.")]
        public decimal? Cost { get; set; }

		[Display(Name = "Voiture")]
		public int VehicleId { get; set; }

		[Display(Name = "Voiture")]
        [ForeignKey("VehicleId")]
        public virtual Vehicle? Vehicle { get; set; }
    }
}

Models/TrimLevel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
	[Display(Name = "Finition")]
	public class TrimLevel
	{
        [Key]
        public int Id { get; set; }

		[Display(Name = "Finition")]
		public string Name { get; set; } = string.Empty;

		[NotMapped]
		[Display(Name = "Modèle")]
		public int ModelId { get; set; }

		[NotMapped]
		public virtual Model? Model { get; set; }
    }
}

Models/Vehicle.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
    public class Vehicle
	{
        [Key]
        public int Id { get; set; }

		[Display(Name = "Code VIN")]
        [StringLength(17, MinimumLength = 17, ErrorMessage = "Le code VIN doit être une chaîne de 17 caractères")]
        [RegularExpression(@"^[A-HJ-NPR-Z0-9]{17}$", ErrorMessage = "Le code VIN doit contenir uniquement des lettres majuscules (à l'exception de I, O, Q) et des chiffres.")]
        public string? Vin { get; set; }

		[Display(Name = "Année*")]
		[Required(ErrorMessage = "Il manque l'année du véhicule")]
		[ValidYear(1990, ErrorMessage = "L'année doit être entre 1990 et l'année en cours.")]
		public int Year { get; set; }

		[Display(Name = "Date d'achat*")]
		[Required(ErrorMessage = "La date d'achat du vehicle doit être complétée.")]
        [DataType(DataType.Date, ErrorMessage = "La date d'achat doit être une date.")]
		[ValidPurchaseDate]
		public DateTime PurchaseDate { get; set; }

		[Display(Name = "Prix d'achat*")]
		[Required(ErrorMessage = "Le prix d'achat du vehicle doit être complétée.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Le prix d'achat doit être supérieur à 0.")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Disponibilité")]
		[DataType(DataType.Date, ErrorMessage = "La date de disponibilité de vente doit être une date.")]
        public DateTime? AvailabilityDate { get; set; }

        [Display(Name = "Date de vente")]
		[DataType(DataType.Date, ErrorMessage = "La date de vente doit être une date.")]
        public DateTime? SaleDate { get; set; }

        [Display(Name = "Marque*")]
        [Required(ErrorMessage = "Il manque la marque")]
        public int BrandId { get; set; }
        [NotMapped]
        public virtual Brand Brand { get; set; }

        [Display(Name = "Modèle*")]
        [Required(ErrorMessage = "Il manque le modèle")]
        public int ModelId { get; set; }
        [NotMapped]
        public virtual Model Model { get; set; }

        [Display(Name = "Finition*")]
        [Required(ErrorMessage = "Il manque la finition")]
        public int TrimLevelId { get; set; }
        [NotMapped]
        public virtual TrimLevel TrimLevel { get; set; }

		[Display(Name = "Description")]
        [StringLength(150, ErrorMessage = "La description ne peut pas dépasser 150 caractères.")]
        public string? Description { get; set; }

		[Display(Name = "Image")]
		[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.jpg|.jpeg|.png|.gif)$", ErrorMessage = "Seules les images avec l'extension .jpg, .jpeg, .png, .gif sont autorisées.")]
		public string? ImagePath { get; set; }

        [NotMapped]
        [Display(Name = "Détails du véhicule")]
        public string VehicleTitle => $"{Year} - {Brand?.Name} {Model?.Name} {TrimLevel?.Name}";

		public ICollection<Repair>? Repairs { get; set; }
		[NotMapped]
		[Display(Name = "Coûts réparations")]
		public decimal? TotalRepairCost => Repairs?.Sum(r => r.Cost) ?? 0;

		[NotMapped]
        [Display(Name = "Prix de vente")]
        public decimal? SalePrice => PurchasePrice + (TotalRepairCost ?? 0) + 500;
	}
}

public class ValidYearAttribute : ValidationAttribute
{
	private readonly int _minYear;

	public ValidYearAttribute(int minYear)
	{
		_minYear = minYear;
	}

	protected override ValidationResult IsValid(object value, ValidationContext validationContext)
	{
		if (value is int year)
		{
			int currentYear = DateTime.Now.Year;
			if (year >= _minYear && year <= currentYear)
			{
				return ValidationResult.Success;
			}
			else
			{
				return new ValidationResult($"L'année doit être entre {_minYear} et l'année en cours.");
			}
		}
		return new ValidationResult("L'année n'est pas valide.");
	}
}

public class ValidPurchaseDateAttribute : ValidationAttribute
{
	protected override ValidationResult IsValid(object value, ValidationContext validationContext)
	{
		if (value is DateTime purchaseDate)
		{
			if (purchaseDate > DateTime.Now)
			{
				return new ValidationResult("La date d'achat ne peut pas être dans le futur.");
			}
		}
		return ValidationResult.Success;
	}
}

Controllers/ModelsController.cs
using System.Drawing.Drawing2D;
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures.Controllers
{
	[IgnoreAntiforgeryToken]
	public class ModelsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public ModelsController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of all models.
		/// </summary>
		/// <returns>A view with the list of models.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Models.Include(m => m.Brand);
			return View(await applicationDbContext.ToListAsync());
		}

		/// <summary>
		/// Gets the details of a specific model.
		/// </summary>
		/// <param name="id">The ID of the model.</param>
		/// <returns>A partial view with the model details.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var model = await _context.Models
				.Include(m => m.Brand)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (model == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", model);
		}

		/// <summary>
		/// Shows the create model form.
		/// </summary>
		/// <returns>A partial view with the create model form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public IActionResult Create()
		{
			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name");
			return PartialView("_CreatePartial");
		}

		/// <summary>
		/// Creates a new model.
		/// </summary>
		/// <param name="model">The model to create.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create partial view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost]
		public async Task<IActionResult> Create([Bind("Id,Name,BrandId")] Model model)
		{
			if (model == null || string.IsNullOrWhiteSpace(model.Name))
			{
				ModelState.AddModelError("Name", "Le nom du modèle est requis.");

				ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", model.BrandId);
				return PartialView("_CreatePartial", model);
			}

			var existingModel = await _context.Models
				.FirstOrDefaultAsync(b => b.Name.ToLower() == model.Name.ToLower());

			if (existingModel != null)
			{
				ModelState.AddModelError("Name", "Un modèle avec ce nom existe déjà.");
			}

			ModelState.Remove("Brand");
			ModelState.Remove("TrimLevels");
			if (ModelState.IsValid)
			{
				_context.Add(model);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", model.BrandId);
			return PartialView("_CreatePartial", model);
		}

		/// <summary>
		/// Shows the edit model form.
		/// </summary>
		/// <param name="id">The ID of the model to edit.</param>
		/// <returns>A partial view with the edit model form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var model = await _context.Models.FindAsync(id);
			if (model == null)
			{
				return NotFound();
			}
			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", model.BrandId);
			return PartialView("_EditPartial", model);
		}

		/// <summary>
		/// Edits a specific model.
		/// </summary>
		/// <param name="id">The ID of the model to edit.</param>
		/// <param name="model">The updated model information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit partial view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,BrandId")] Model model)
		{
			if (id != model.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(model);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ModelExists(model.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", model.BrandId);
			return PartialView("_EditPartial", model);
		}

		/// <summary>
		/// Shows the delete model confirmation form.
		/// </summary>
		/// <param name="id">The ID of the model to delete.</param>
		/// <returns>A partial view with the delete model confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var model = await _context.Models
				.Include(m => m.Brand)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (model == null)
			{
				return NotFound();
			}

			return PartialView("_DeletePartial", model);
		}

		/// <summary>
		/// Deletes a specific model.
		/// </summary>
		/// <param name="id">The ID of the model to delete.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			try
			{
				var model = await _context.Models.FindAsync(id);
				if (model != null)
				{
					_context.Models.Remove(model);
				}

				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorDeleteMessage"] = "Ce modèle ne peut pas être supprimé car il est utilisé pour un ou plusieurs véhicules, ou il est lié à une marque ou contient des finitions. Veuillez supprimer ces éléments avant de procéder.";
                return RedirectToAction(nameof(Index));
            }
        }

		/// <summary>
		/// Checks if a model exists.
		/// </summary>
		/// <param name="id">The ID of the model to check.</param>
		/// <returns>True if the model exists, otherwise false.</returns>
		private bool ModelExists(int id)
		{
			return _context.Models.Any(e => e.Id == id);
		}
	}
}

Views/Models/Index.cshtml
@model IEnumerable<ExpressVoitures.Models.Model>

@{
    ViewData["Title"] = "Les modèles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ErrorDeleteMessage = TempData["ErrorDeleteMessage"] as string;
}

<h1 class="text-center mt-5">Les modèles</h1>

<div class="col-lg-8 mx-auto">
    <div class="d-flex flex-row justify-content-end mt-5 mb-3">
        <a class="btn btn-primary" href="javascript:void(0);" onclick="loadModal('@Url.Action("Create", "Models")', null, 'Ajouter un modèle', false)" );">
            Ajouter
        </a>
    </div>

    <div class="p-4 rounded bg-white shadow-lg">
        <table class="table align-middle"
               data-locale="fr-FR"
               data-toggle="table"
               data-id-field="id"
               data-pagination="true"
               data-page-list="[10, 25, 50, 100, all]"
               data-search="true">
            <thead class="table-light">
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th data-sortable="true">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th data-sortable="true">
                    @Html.DisplayNameFor(model => model.Brand)
                </th>
                <th scope="col" class="text-end">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand.Name)
                    </td>
                    <td class="text-end">
                        <div class="btn-group">
                                <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Edit", "Models")', @item.Id, 'Modifier un modèle')" class="btn btn-secondary btn-sm">Modifier</a>

                            <button type="button" class="btn btn-secondary btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden">Toggle Dropdown</span>
                            </button>

                            <ul class="dropdown-menu">
                                <li>
                                        <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Details", "Models")', @item.Id, 'Détail du modèle')" class="dropdown-item">
                                        <i class="bi bi-eye-fill"></i> Voir</a>
                                </li>
                                <li>
                                        <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Delete", "Models")', @item.Id, 'Supprimer le modèle')" class="dropdown-item">
                                        <i class="bi bi-trash-fill"></i> Supprimer</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>

@if (!string.IsNullOrEmpty(ErrorDeleteMessage))
{
    <div class="modal fade" id="ErrorDeleteMessage" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content panel-warning">
                <div class="modal-header panel-heading">
                    <h1 class="modal-title fs-5" id="modalLabel">Erreur de suppression</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
                </div>
                <div class="modal-body text-center">
                    <div class="alert alert-danger" role="alert">
                        <i class="bi bi-exclamation-circle-fill"></i>
                        <div>@ErrorDeleteMessage</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var ErrorDeleteMessage = document.getElementById('ErrorDeleteMessage');
            var bootstrapModal = new bootstrap.Modal(ErrorDeleteMessage);
            bootstrapModal.show();
        });
    </script>
}

Views/Models/_CreatePartial.cshtml
@model ExpressVoitures.Models.Model

<form asp-action="Create" id="createForm" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3 form-group">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label asp-for="BrandId" class="form-label"></label>
        <select asp-for="BrandId" class="form-control" data-live-search="true" data-size="20" asp-items="ViewBag.BrandId"></select>
    </div>

    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Créer" class="btn btn-primary" />
    </div>
</form>

Views/Models/_DeletePartial.cshtml
@model ExpressVoitures.Models.Model

<dl class="row text-center">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />
    </div>
</form>

Views/Models/_DetailsPartial.cshtml
@model ExpressVoitures.Models.Model

<dl class="row text-center">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

<div class="mt-5 d-flex flex-row justify-content-between text-center">
    <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
</div>

Views/Models/_EditPartial.cshtml
@model ExpressVoitures.Models.Model

@{
    ViewData["Title"] = "Modifier";
}

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="BrandId" class="form-label"></label>
        <select asp-for="BrandId" class="form-select" asp-items="ViewBag.BrandId" disabled></select>
        <input type="hidden" asp-for="BrandId" />
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>

    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Modifier" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}