Models/Repair.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
    [Display(Name = "Réparation")]
    public class Repair
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Réparation")]
        [Required(ErrorMessage = "La réparation doit être complétée.")]
        public string Name { get; set; } = string.Empty;

		[Display(Name = "Coût")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Le coût doit être supérieur à 0.")]
        public decimal? Cost { get; set; }

		[Display(Name = "Voiture")]
		public int VehicleId { get; set; }

		[Display(Name = "Voiture")]
        [ForeignKey("VehicleId")]
        public virtual Vehicle? Vehicle { get; set; }
    }
}

Controllers/RepairsController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures.Controllers
{
	[IgnoreAntiforgeryToken]
	public class RepairsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public RepairsController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of repairs for a specific vehicle.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <returns>A view with the list of repairs.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{vehicleId}/repair")]
		public async Task<IActionResult> Index(int vehicleId)
		{
            var vehicle = await _context.Vehicle.FirstOrDefaultAsync(v => v.Id == vehicleId);

            if (vehicle == null)
			{
				return NotFound();
			}

			var totalRepairCost = vehicle.Repairs?.Sum(r => r.Cost) ?? 0;

			var repairs = await _context.Repair
				.Where(r => r.VehicleId == vehicleId)
				.ToListAsync();

            ViewBag.VehicleId = vehicleId;
            ViewData["TotalRepairCost"] = totalRepairCost;

			return View(repairs);
		}

		/// <summary>
		/// Shows the create repair form for a specific vehicle.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <returns>A view with the create repair form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{vehicleId}/repair/add")]
		public IActionResult Create(int vehicleId)
		{
			var vehicle = _context.Vehicle.Find(vehicleId);

			if (vehicle == null)
			{
				return NotFound();
			}

			ViewData["VehicleId"] = new SelectList(_context.Vehicle, "Id", "Id", vehicleId);

			return View(new Repair { VehicleId = vehicleId });
		}

		/// <summary>
		/// Creates a new repair for a specific vehicle.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <param name="repair">The repair to create.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/{vehicleId}/repair/add")]
		public async Task<IActionResult> Create(int vehicleId, [Bind("Id,Name,Cost,VehicleId")] Repair repair)
		{
			ModelState.Remove("Vehicle");
			if (ModelState.IsValid)
			{
				_context.Add(repair);
				await _context.SaveChangesAsync();

				return RedirectToAction("Index", new { vehicleId });
			}

			ViewData["VehicleId"] = new SelectList(_context.Vehicle, "Id", "Id", repair.VehicleId);

			return View(repair);
		}

		/// <summary>
		/// Shows the edit repair form for a specific repair.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <param name="id">The ID of the repair.</param>
		/// <returns>A view with the edit repair form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{vehicleId}/repair/edit/{id}")]
		public async Task<IActionResult> Edit(int vehicleId, int id)
		{
			var repair = await _context.Repair.FindAsync(id);

			if (repair == null)
			{
				return NotFound();
			}

			ViewData["VehicleId"] = new SelectList(_context.Vehicle, "Id", "Id", repair.VehicleId);

			return View(repair);
		}

		/// <summary>
		/// Edits a specific repair.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <param name="id">The ID of the repair.</param>
		/// <param name="repair">The updated repair information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/{vehicleId}/repair/edit/{id}")]
		public async Task<IActionResult> Edit(int vehicleId, int id, [Bind("Id,Name,Cost,VehicleId")] Repair repair)
		{
			if (id != repair.Id)
			{
				return NotFound();
			}

			ModelState.Remove("Vehicle");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(repair);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!RepairExists(repair.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction("Index", new { vehicleId });
			}

			ViewData["VehicleId"] = new SelectList(_context.Vehicle, "Id", "Id", repair.VehicleId);

			return View(repair);
		}

		/// <summary>
		/// Shows the delete repair confirmation form for a specific repair.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <param name="id">The ID of the repair.</param>
		/// <returns>A view with the delete repair confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{vehicleId}/repair/delete/{id}")]
		public async Task<IActionResult> Delete(int vehicleId, int id)
		{
			var repair = await _context.Repair
				.Include(r => r.Vehicle)
				.FirstOrDefaultAsync(m => m.Id == id);

			if (repair == null)
			{
				return NotFound();
			}

			return View(repair);
		}

		/// <summary>
		/// Deletes a specific repair.
		/// </summary>
		/// <param name="vehicleId">The ID of the vehicle.</param>
		/// <param name="id">The ID of the repair.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/{vehicleId}/repair/delete/{id}"), ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int vehicleId, int id)
		{
			var repair = await _context.Repair.FindAsync(id);

			if (repair != null)
			{
				_context.Repair.Remove(repair);
			}

			await _context.SaveChangesAsync();

			return RedirectToAction("Index", new { vehicleId });
		}

		/// <summary>
		/// Checks if a repair exists.
		/// </summary>
		/// <param name="id">The ID of the repair to check.</param>
		/// <returns>True if the repair exists, otherwise false.</returns>
		private bool RepairExists(int id)
		{
			return _context.Repair.Any(e => e.Id == id);
		}
	}
}

Controllers/VehiclesController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.PixelFormats;

namespace ExpressVoitures.Controllers
{
	[IgnoreAntiforgeryToken]
	public class VehiclesController : Controller
	{
		private readonly ApplicationDbContext _context;

		public VehiclesController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of vehicles.
		/// </summary>
		/// <returns>A view with the list of vehicles.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle")]
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
				.Include(v => v.Repairs);

            return View(await applicationDbContext.ToListAsync());
		}

		/// <summary>
		/// Gets the details of a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A partial view with the vehicle details.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/details")]
		public async Task<IActionResult> Details(int id)
		{
			var vehicle = await _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
                .Include(v => v.Repairs)
                .FirstOrDefaultAsync(m => m.Id == id);

			if (vehicle == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", vehicle);
		}

		/// <summary>
		/// Shows the create vehicle form.
		/// </summary>
		/// <returns>A view with the create vehicle form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/add")]
		public IActionResult Create()
		{
			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name");
			return View();
		}

		/// <summary>
		/// Creates a new vehicle.
		/// </summary>
		/// <param name="vehicle">The vehicle to create.</param>
		/// <param name="ImagePath">The image file to upload.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/add")]
		public async Task<IActionResult> Create([Bind("Id,Vin,Year,PurchaseDate,PurchasePrice,AvailabilityDate,SaleDate,BrandId,ModelId,TrimLevelId,Description")] Vehicle vehicle, IFormFile ImagePath)
		{
			if (ImagePath != null && ImagePath.Length > 0)
			{
				var extension = Path.GetExtension(ImagePath.FileName);

				var fileName = Path.GetFileNameWithoutExtension(ImagePath.FileName);
				fileName = fileName.Replace(" ", "-");
				fileName = string.Concat(fileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)));
				fileName = $"{fileName}_{DateTime.Now:yyyyMMddHHmmss}{extension}".ToLower();

				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/adverts", fileName);

				using (var image = await SixLabors.ImageSharp.Image.LoadAsync<Rgba32>(ImagePath.OpenReadStream()))
				{
					// Redimensionner l'image à 800x600
					image.Mutate(x => x.Resize(new ResizeOptions
					{
						Size = new Size(800, 600),
						Mode = ResizeMode.Crop
					}));

					await image.SaveAsync(filePath, new JpegEncoder());
				}

				vehicle.ImagePath = "/images/adverts/" + fileName;
			}

			ModelState.Remove("Brand");
			ModelState.Remove("Model");
			ModelState.Remove("TrimLevel");
			ModelState.Remove("ImagePath");
			if (ModelState.IsValid)
			{
				_context.Add(vehicle);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Shows the edit vehicle form for a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A view with the edit vehicle form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/edit")]
		public async Task<IActionResult> Edit(int id)
		{
			var vehicle = await _context.Vehicle.FindAsync(id);
			if (vehicle == null)
			{
				return NotFound();
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Edits a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <param name="vehicle">The updated vehicle information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit view.</returns>
		[Authorize]
		[HttpPost("/admin/vehicle/{id}/edit")]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Vin,Year,PurchaseDate,PurchasePrice,AvailabilityDate,SaleDate,BrandId,ModelId,TrimLevelId,Description")] Vehicle vehicle, IFormFile ImagePath)
		{
			if (id != vehicle.Id)
			{
				return NotFound();
			}

			var existingVehicle = await _context.Vehicle.AsNoTracking().FirstOrDefaultAsync(v => v.Id == id);
			if (existingVehicle == null)
			{
				return NotFound();
			}

			if (ImagePath != null && ImagePath.Length > 0)
			{
				var extension = Path.GetExtension(ImagePath.FileName);

				var fileName = Path.GetFileNameWithoutExtension(ImagePath.FileName);
				fileName = fileName.Replace(" ", "-");
				fileName = string.Concat(fileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)));
				fileName = $"{fileName}_{DateTime.Now:yyyyMMddHHmmss}{extension}".ToLower();

				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/adverts", fileName);

				using (var image = await Image.LoadAsync<Rgba32>(ImagePath.OpenReadStream()))
				{
					var destWidth = 1280;
					var destHeight = 720;

					// Calculate cropping rectangle
					var cropRect = new Rectangle(0, 0, image.Width, image.Height);
					if ((image.Width / (double)image.Height) > (16 / 9.0))
					{
						var newWidth = (int)(image.Height * (16 / 9.0));
						cropRect.X = (image.Width - newWidth) / 2;
						cropRect.Width = newWidth;
					}
					else
					{
						var newHeight = (int)(image.Width * (9 / 16.0));
						cropRect.Y = (image.Height - newHeight) / 2;
						cropRect.Height = newHeight;
					}

					// Crop and resize the image
					image.Mutate(x => x
						.Crop(cropRect)
						.Resize(destWidth, destHeight));

					await image.SaveAsync(filePath, new JpegEncoder());
				}

				vehicle.ImagePath = "/images/adverts/" + fileName;
			}
			else
			{
				vehicle.ImagePath = existingVehicle.ImagePath;
			}

			ModelState.Remove("Brand");
			ModelState.Remove("Model");
			ModelState.Remove("TrimLevel");
			ModelState.Remove("ImagePath");
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(vehicle);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!VehicleExists(vehicle.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}

			ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", vehicle.BrandId);
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", vehicle.ModelId);
			ViewData["TrimLevelId"] = new SelectList(_context.TrimLevels, "Id", "Name", vehicle.TrimLevelId);
			return View(vehicle);
		}

		/// <summary>
		/// Shows the delete vehicle confirmation form for a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A partial view with the delete vehicle confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpGet("/admin/vehicle/{id}/delete")]
		public async Task<IActionResult> Delete(int id)
		{
			var vehicle = await _context.Vehicle
				.Include(v => v.Brand)
				.Include(v => v.Model)
				.Include(v => v.TrimLevel)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (vehicle == null)
			{
				return NotFound();
			}

			return PartialView("_DeletePartial", vehicle);
		}

		/// <summary>
		/// Deletes a specific vehicle.
		/// </summary>
		/// <param name="id">The ID of the vehicle.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost("/admin/vehicle/{id}/delete"), ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var vehicle = await _context.Vehicle.FindAsync(id);
			if (vehicle != null)
			{
				_context.Vehicle.Remove(vehicle);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		/// <summary>
		/// Checks if a vehicle exists.
		/// </summary>
		/// <param name="id">The ID of the vehicle to check.</param>
		/// <returns>True if the vehicle exists, otherwise false.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		private bool VehicleExists(int id)
		{
			return _context.Vehicle.Any(e => e.Id == id);
		}

		/// <summary>
		/// Gets the models based on BrandId.
		/// </summary>
		/// <param name="brandId">The ID of the brand.</param>
		/// <returns>A JSON result with the list of models.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<JsonResult> GetModelsByBrand(int brandId)
		{
			var models = await _context.Models.Where(m => m.BrandId == brandId).ToListAsync();
			return Json(new SelectList(models, "Id", "Name"));
		}

		/// <summary>
		/// Gets the trim levels based on ModelId.

Views/Repairs/Create.cshtml
@model ExpressVoitures.Models.Repair

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center my-5">Ajouter une réparation</h1>

<div class="row">
    <div class="col-lg-6 mx-auto p-4 rounded bg-white shadow-lg">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Cost" class="form-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>

            <div class="mb-3 d-none">
                <label asp-for="VehicleId" class="form-label"></label>
                <select asp-for="VehicleId" class="form-select" asp-items="ViewBag.VehicleId" disabled></select>
            </div>

            <div class="mt-5 form-group d-flex flex-row justify-content-between form-group text-center">
                <a asp-action="Index" asp-route-vehicleId="@Model.VehicleId" class="btn btn-outline-secondary">Retour</a>
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Repairs/Delete.cshtml
@model ExpressVoitures.Models.Repair

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center my-5">Delete</h1>

<div class="col-lg-6 mx-auto p-4 rounded bg-white shadow-lg">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="mt-5 form-group d-flex flex-row justify-content-between form-group text-center">
            <a asp-action="Index" asp-route-vehicleId="@Model.VehicleId" class="btn btn-outline-secondary">Retour</a>
            <input type="submit" value="Supprimer" class="btn btn-danger" />
        </div>
    </form>
</div>

Views/Repairs/Edit.cshtml
@model ExpressVoitures.Models.Repair

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center my-5">Edit</h1>

<div class="row">
    <div class="col-lg-6 mx-auto p-4 rounded bg-white shadow-lg">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Cost" class="form-label"></label>
                <input asp-for="Cost" class="form-control" />
                <span asp-validation-for="Cost" class="text-danger"></span>
            </div>

            <div class="mb-3 d-none">
                <label asp-for="VehicleId" class="form-label"></label>
                <select asp-for="VehicleId" class="form-control" asp-items="ViewBag.VehicleId" disabled></select>
                <span asp-validation-for="VehicleId" class="text-danger"></span>
            </div>

            <div class="mt-5 form-group d-flex flex-row justify-content-between form-group text-center">
                <a asp-action="Index" asp-route-vehicleId="@Model.VehicleId" class="btn btn-outline-secondary">Retour</a>
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Repairs/Index.cshtml
@model IEnumerable<ExpressVoitures.Models.Repair>

@{
    ViewData["Title"] = "Les réparations";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var totalRepairCost = Model.Sum(item => item.Cost);
}

<h1 class="text-center mt-5">Les réparations</h1>

<div class="col-lg-8 mx-auto">
    <div class="d-flex flex-row justify-content-end mt-5 mb-4">
        <a class="btn btn-primary" asp-controller="Repairs" asp-action="Create" asp-route-vehicleId="@ViewBag.VehicleId">
            Ajouter
        </a>
    </div>

    <div class="table-responsive p-4 rounded bg-white shadow-lg">
        <table class="table">
            <thead class="table-light">
                <tr>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Cost)
                    </th>
                    <th scope="col" class="text-end">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model) {
                @if (item.Id != 0)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                        @if (item.Cost != null)
                        {
                            @:@String.Format("{0:F2} €", item.Cost)
                        }
                        </td>
                        <td class="text-end">
                            <div class="btn-group">
                                <a asp-action="Edit" asp-route-vehicleId="@item.VehicleId" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Modifier</a>

                                <button type="button" class="btn btn-secondary btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="visually-hidden">Toggle Dropdown</span>
                                </button>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a asp-action="Delete" asp-route-vehicleId="@item.VehicleId" asp-route-id="@item.Id" class="dropdown-item text-danger">
                                            <i class="bi bi-trash-fill"></i> Supprimer
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            }
            </tbody>
            <tfoot>
                <tr>
                    <td>
                        <b>Total</b>
                    </td>
                    <td>
                        @if (@totalRepairCost != 0)
                        {
                            <b>@String.Format("{0:F2} €", totalRepairCost)</b>
                        }
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="form-group mt-4">
        <a asp-controller="Vehicles" asp-action="Index" class="btn btn-outline-secondary">Retour</a>
    </div>
</div>