Models/TrimLevel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExpressVoitures.Models
{
	[Display(Name = "Finition")]
	public class TrimLevel
	{
        [Key]
        public int Id { get; set; }

		[Display(Name = "Finition")]
		public string Name { get; set; } = string.Empty;

		[NotMapped]
		[Display(Name = "Modèle")]
		public int ModelId { get; set; }

		[NotMapped]
		public virtual Model? Model { get; set; }
    }
}

Controllers/TrimLevelsController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ExpressVoitures
{
	[IgnoreAntiforgeryToken]
	public class TrimLevelsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public TrimLevelsController(ApplicationDbContext context)
		{
			_context = context;
		}

		/// <summary>
		/// Gets the list of all trim levels.
		/// </summary>
		/// <returns>A view with the list of trim levels.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Index()
		{
			var applicationDbContext = _context.TrimLevels
				.Include(t => t.Model)
				.ThenInclude(m => m.Brand);

			return View(await applicationDbContext.ToListAsync());
		}

		/// <summary>
		/// Gets the details of a specific trim level.
		/// </summary>
		/// <param name="id">The ID of the trim level.</param>
		/// <returns>A partial view with the trim level details.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var trimLevel = await _context.TrimLevels
				.Include(t => t.Model)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (trimLevel == null)
			{
				return NotFound();
			}

			return PartialView("_DetailsPartial", trimLevel);
		}

		/// <summary>
		/// Shows the create trim level form.
		/// </summary>
		/// <returns>A partial view with the create trim level form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public IActionResult Create()
		{
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name");
			return PartialView("_CreatePartial");
		}

		/// <summary>
		/// Creates a new trim level.
		/// </summary>
		/// <param name="trimLevel">The trim level to create.</param>
		/// <returns>A redirect to the index view if successful, otherwise the create partial view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost]
		public async Task<IActionResult> Create([Bind("Id,Name,ModelId")] TrimLevel trimLevel)
		{
			if (trimLevel == null || string.IsNullOrWhiteSpace(trimLevel.Name))
			{
				ModelState.AddModelError("Name", "Le nom de la finition est requis.");

				ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", trimLevel.ModelId);
				return PartialView("_CreatePartial", trimLevel);
			}

			var existingTrimLevel = await _context.TrimLevels
				.FirstOrDefaultAsync(b => b.Name.ToLower() == trimLevel.Name.ToLower());

			if (existingTrimLevel != null)
			{
				ModelState.AddModelError("Name", "Une finition avec ce nom existe déjà.");
			}

			ModelState.Remove("Brand");
			ModelState.Remove("Model");
			if (ModelState.IsValid)
			{
				_context.Add(trimLevel);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", trimLevel.ModelId);
			return PartialView("_CreatePartial", trimLevel);
		}

		/// <summary>
		/// Shows the edit trim level form.
		/// </summary>
		/// <param name="id">The ID of the trim level to edit.</param>
		/// <returns>A partial view with the edit trim level form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var trimLevel = await _context.TrimLevels.FindAsync(id);
			if (trimLevel == null)
			{
				return NotFound();
			}
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", trimLevel.ModelId);
			return PartialView("_EditPartial", trimLevel);
		}

		/// <summary>
		/// Edits a specific trim level.
		/// </summary>
		/// <param name="id">The ID of the trim level to edit.</param>
		/// <param name="trimLevel">The updated trim level information.</param>
		/// <returns>A redirect to the index view if successful, otherwise the edit partial view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ModelId")] TrimLevel trimLevel)
		{
			if (id != trimLevel.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(trimLevel);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!TrimLevelExists(trimLevel.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Name", trimLevel.ModelId);
			return PartialView("_EditPartial", trimLevel);
		}

		/// <summary>
		/// Shows the delete trim level confirmation form.
		/// </summary>
		/// <param name="id">The ID of the trim level to delete.</param>
		/// <returns>A partial view with the delete trim level confirmation form.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var trimLevel = await _context.TrimLevels
				.Include(t => t.Model)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (trimLevel == null)
			{
				return NotFound();
			}

			return PartialView("_DeletePartial", trimLevel);
		}

		/// <summary>
		/// Deletes a specific trim level.
		/// </summary>
		/// <param name="id">The ID of the trim level to delete.</param>
		/// <returns>A redirect to the index view.</returns>
		[Authorize]
		[IgnoreAntiforgeryToken]
		[HttpPost, ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
            try
            {
                var trimLevel = await _context.TrimLevels.FindAsync(id);
				if (trimLevel != null)
				{
					_context.TrimLevels.Remove(trimLevel);
				}

				await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorDeleteMessage"] = "Cette finition ne peut pas être supprimée car elle est utilisée pour un ou plusieurs véhicules, ou elle est liée à une marque et à un modèle. Veuillez supprimer ces éléments avant de procéder.";
                return RedirectToAction(nameof(Index));
            }
        }

		/// <summary>
		/// Checks if a trim level exists.
		/// </summary>
		/// <param name="id">The ID of the trim level to check.</param>
		/// <returns>True if the trim level exists, otherwise false.</returns>
		private bool TrimLevelExists(int id)
		{
			return _context.TrimLevels.Any(e => e.Id == id);
		}
	}
}

Views/TrimLevels/Index.cshtml
@model IEnumerable<ExpressVoitures.Models.TrimLevel>

@{
    ViewData["Title"] = "Les finitions";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ErrorDeleteMessage = TempData["ErrorDeleteMessage"] as string;
}

<h1 class="text-center mt-5">Les finitions</h1>

<div class="col-lg-8 mx-auto">
    <div class="d-flex flex-row justify-content-end mt-5 mb-3">
        <a class="btn btn-primary" href="javascript:void(0);" onclick="loadModal('@Url.Action("Create", "TrimLevels")', null, 'Ajouter une finition', false)" );">
            Ajouter
        </a>
    </div>

    <div class="p-4 rounded bg-white shadow-lg">
        <table class="table align-middle"
               data-locale="fr-FR"
               data-toggle="table"
               data-id-field="id"
               data-pagination="true"
               data-page-list="[10, 25, 50, 100, all]"
               data-search="true">
            <thead class="table-light">
            <tr>
                <th data-field="id" data-sortable="true">
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th data-sortable="true">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th data-sortable="true">
                    @Html.DisplayNameFor(model => model.Model)
                </th>
                <th sdata-sortable="true">
                    @Html.DisplayNameFor(model => model.Model.Brand.Name)
                </th>
                <th data-sortable="true" class="text-end">
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model.Brand.Name)
                    </td>
                    <td class="text-end">
                        <div class="btn-group">
                                <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Edit", "TrimLevels")', @item.Id, 'Modifier une finition', false)" class="btn btn-secondary btn-sm">Modifier</a>

                            <button type="button" class="btn btn-secondary btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden">Toggle Dropdown</span>
                            </button>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Details", "TrimLevels")', @item.Id, 'Détail de la finition', false)" class="dropdown-item">
                                    <i class="bi bi-eye-fill"></i> Voir</a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);" onclick="loadModal('@Url.Action("Delete", "TrimLevels")', @item.Id, 'Supprimer la finition', false)" class="dropdown-item">
                                    <i class="bi bi-trash-fill"></i> Supprimer</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="Modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel"></h1>
                <button type="button" class="btn-close" aria-label="Fermer"></button>
            </div>
            <div class="modal-body"></div>
        </div>
    </div>
</div>

@if (!string.IsNullOrEmpty(ErrorDeleteMessage))
{
    <div class="modal fade" id="ErrorDeleteMessage" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalLabel">Erreur de suppression</h1>
                    <button type="button" class="btn-close" aria-label="Fermer"></button>
                </div>
                <div class="modal-body text-center">
                    <div class="alert alert-danger" role="alert">
                        <i class="bi bi-exclamation-circle-fill"></i>
                        <div>@ErrorDeleteMessage</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var ErrorDeleteMessage = document.getElementById('ErrorDeleteMessage');
            var bootstrapModal = new bootstrap.Modal(ErrorDeleteMessage);
            bootstrapModal.show();
        });
    </script>
}

Views/TrimLevels/_CreatePartial.cshtml
@model ExpressVoitures.Models.TrimLevel

<form asp-action="Create" id="createForm" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="mb-3 form-group">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3 form-group">
        <label asp-for="ModelId" class="form-label"></label>
        <select asp-for="ModelId" class="form-control" data-live-search="true" data-size="20" asp-items="ViewBag.ModelId"></select>
    </div>

    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Créer" class="btn btn-primary" />
    </div>
</form>

Views/TrimLevels/_DeletePartial.cshtml
@model ExpressVoitures.Models.TrimLevel

<dl class="row text-center">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />
    </div>
</form>

Views/TrimLevels/_DetailsPartial.cshtml
@model ExpressVoitures.Models.TrimLevel

<dl class="row text-center">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

<div class="mt-5 d-flex flex-row justify-content-between text-center">
    <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
</div>

Views/TrimLevels/_EditPartial.cshtml
@model ExpressVoitures.Models.TrimLevel

@{
    ViewData["Title"] = "Modifier";
}

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="ModelId" class="form-label"></label>
        <select asp-for="ModelId" class="form-select" asp-items="ViewBag.ModelId" disabled></select>
        <input type="hidden" asp-for="ModelId" />
        <span asp-validation-for="ModelId" class="text-danger"></span>
    </div>

    <div class="mt-5 d-flex flex-row justify-content-between text-center">
        <a asp-action="Index" class="btn btn-outline-secondary">Retour</a>
        <input type="submit" value="Modifier" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}